[package]
name = "bijon"
version = "0.1.0"
authors = ["re:Zer0dAI <tutti@frutti.com>"]

[lib]
name = "libbijon"
path = "src/lib.rs"
doc = false

[dependencies]
core = { path = "../../core" }
generic = { path = "../../generic" }
common = { path = "../common" }
libc = "0.2.109"
