online = ["liblimiter", "libsyncer", "libraceunlock", "libbfl"]#, "libdebug"]#"libfilter"] "libpoclog",

[core.bfl]
magic = 66
debug = true#false#
max_inserts = 7
max_allowed_wait_count_per_call = 66#200#888
is_strict_repro = true
shmem = 0
pocmem = 0

[core.debug]
noisy = true#false#
ctors_included = true#false#
mask = 65535#
only_successfull = false#true#

[core.poclog]
addr = 8589934592
size = 104857600
flush2file = true
fname = "bpoc"
printout = false#true

[core.raceunlock]
sleep = 0
racer_count = 6

[core.overpoc]
size_of_log = 200

[core.limiter]
num_of_calls = 200
failed_limit = 666#1000

[core.grayfuzz]
path = "./"
extension = ""
cc_module = ["libcorpus"]
lib_count = 15
entry_point = "do_poc"
oscilate_count = 6
after_fuzz_count = 10
racer_count = 3
wait_ms = 100
skip_ctors = true

[core.filter.whitelist]
ctors = 0
