[package]
name = "api"
version = "0.2.0"
authors = ["re:Zer0dAI <team@bananas.com>"]

[dependencies]
rand = "0.8.4"
byteorder = { version = "1.4.3" }
core = { path = "../core" }
generic = { path = "../generic" }

